### PR TITLE
Add border radius property to BlurView and VibrancyView

### PR DESCRIPTION
**Pull request by chagasaway**
Hey, I have been using this project for a while and in my project I had to use the blurred view with corned radius.

So I am pull requesting the changes I have made that made possible to add a border radius to the container, maybe it will be useful because it's a well used style for containers.

If you have any questions feel free to contact me.

### CODE REVIEW

**Comment by Kureev** [comment]
Hello @chagasaway!
Thanks for contributing this project, I'm glad to hear you're using it. 
I have some questions about this PR: can you explain me, why you can't use `style` property or compose it with high-order component to achieve `border-radius` effect:

```jsx
<BlurView style={{ borderRadius: 10, }}></BlurView>
```
or
```jsx
<View style={{ borderRadius: 10, }}>
  <BlurView>...</BlurView>
</View>
```

**Comment by chagasaway** [comment]
Hey @Kureev, thanks for the answer!

I have tried both ways in the past and I could not achieve the behaviour without the modifications in the library files.

Here is the result of this code (https://gist.github.com/chagasaway/15a59ba45b78fc1de57d) where I try the both ways you suggested.

simulator screen shot nov 19 2015 12 15 30

**Comment by Kureev** [comment]
Well, I'm not quite sure, but probably it's because I'm not inherited from RCTView in my files.
I'll appreciate if you'll be so kind to test it (replace UIView by RCTView) and let me know

**Comment by chagasaway** [comment]
Hey @Kureev, I have replaced the UIView references to RCTView and could not achieve the behaviour as well.

Here is the branch where I have made the changes for you analysis: 

https://github.com/chagasaway/react-native-blur/tree/change-uiview-rctview

Do you have any other possible idea?

**Comment by sbugert** [comment]
I also had the idea in my project to use borderRadius with react-native-blur so I started experimenting changing the source to make it work.

Turns out all you need to do is adding `self.clipsToBounds = YES;` to make it work. This will clip the subview's (the UIVisualEffectView in this case) to the UIViews bounds.
No need to add another prop, this way the standard inline style attribute can be used just like with a RCTView.

Should I open another PR so you can take a look at it?

**Comment by grabbou** [comment]
Have you tried setting overflow on parent component? Should work just like in CSS with borders.

**Comment by chagasaway** [comment]
Hey @sbugert I have made the changes that you suggested to this pull request branch but testing here only adding the clipToBounds did not solve the issue with the borderRadius.

Maybe I have added it at the wrong place or something else, could you do a double check for me?

Thanks for the help!

**Comment by sbugert** [comment]
I commented your commit.
But I received an email from Github that someone suggested
> Have you tried setting overflow on parent component? Should work just like in CSS with borders.

So I tried to set overflow to 'hidden' and it works for my case.

**Comment by chagasaway** [comment]
Yeah @sbugert, I tried the overflow here and it worked.

simulator screen shot dec 2 2015 19 50 46

I am closing this PR.

Thanks for the help!

**Pull request closed without merging**
